# Generated by Django 4.2.1 on 2023-05-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vladimirova_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='epoch_title',
            field=models.CharField(default='222', max_length=100, verbose_name='Эпоха'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=100, verbose_name='Варианты ответа'),
        ),
    ]
