# Generated by Django 4.2.1 on 2023-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vladimirova_app', '0002_choice_answer_status_question_epoch_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer_status',
            field=models.BooleanField(default=False, verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='epoch_title',
            field=models.CharField(max_length=100, verbose_name='Эпоха'),
        ),
    ]
