# Generated by Django 4.2.1 on 2023-05-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vladimirova_app', '0003_alter_choice_answer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='epoch_title',
            field=models.CharField(choices=[('Древняя Русь', 'Древняя Русь'), ('Русское государство', 'Русское государство'), ('Российская Империя', 'Российская Империя')], max_length=200, verbose_name='Эпоха'),
        ),
    ]
