# Generated by Django 4.2.1 on 2023-05-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vladimirova_app', '0004_alter_question_epoch_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='radiobox_class',
            field=models.CharField(default='radiobox_inactive', max_length=100),
        ),
    ]
