# Generated by Django 4.2 on 2023-04-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=400)),
                ('style', models.CharField(max_length=20)),
                ('age_restriction', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
