# Generated by Django 4.2 on 2023-04-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_book_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='style',
            field=models.CharField(max_length=200),
        ),
    ]
