# Generated by Django 4.2.1 on 2023-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheronov_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=100, verbose_name='title')),
                ('film_director', models.CharField(max_length=100, verbose_name='director')),
                ('film_genre', models.CharField(max_length=100, verbose_name='genre')),
                ('film_feedback', models.CharField(max_length=1000, verbose_name='feedback')),
                ('film_promo', models.CharField(max_length=1000, verbose_name='feedback')),
                ('movie_viewed', models.BooleanField(default=False, verbose_name='feedback')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
