# Generated by Django 4.2.1 on 2023-05-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheronov_app', '0002_notefilm_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notefilm',
            old_name='film_director',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='notefilm',
            old_name='film_feedback',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='notefilm',
            old_name='film_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='notefilm',
            old_name='film_promo',
            new_name='promo',
        ),
        migrations.RenameField(
            model_name='notefilm',
            old_name='film_title',
            new_name='title',
        ),
    ]
